"""Initial migration

Revision ID: 2ca02fecce5b
Revises: 
Create Date: 2025-03-16 12:55:34.099344

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2ca02fecce5b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #with op.batch_alter_table('cart', schema=None) as batch_op:
        #batch_op.drop_constraint('cart_ibfk_1', type_='foreignkey')
        #batch_op.create_foreign_key(None, 'product', ['productid'], ['productid'])

    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.alter_column('customername',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=80),
               existing_nullable=False)
        batch_op.alter_column('emailid',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=120),
               existing_nullable=False)
        batch_op.alter_column('password',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.String(length=120),
               existing_nullable=False)

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('productid', sa.Integer(), nullable=False))
        batch_op.alter_column('productname',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('price',
               existing_type=mysql.INTEGER(display_width=10),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.alter_column('image',
               existing_type=mysql.VARCHAR(length=225),
               type_=sa.String(length=255),
               nullable=False)
        batch_op.drop_column('Productid')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Productid', mysql.INTEGER(display_width=50), autoincrement=True, nullable=False))
        batch_op.alter_column('image',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=225),
               nullable=True)
        batch_op.alter_column('price',
               existing_type=sa.Float(),
               type_=mysql.INTEGER(display_width=10),
               existing_nullable=False)
        batch_op.alter_column('productname',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.drop_column('productid')

    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=120),
               type_=mysql.VARCHAR(length=10),
               existing_nullable=False)
        batch_op.alter_column('emailid',
               existing_type=sa.String(length=120),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.alter_column('customername',
               existing_type=sa.String(length=80),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)

   # with op.batch_alter_table('cart', schema=None) as batch_op:
       # batch_op.drop_constraint(None, type_='foreignkey')
        #batch_op.create_foreign_key('cart_ibfk_1', 'product', ['productid'], ['Productid'], ondelete='CASCADE')

    # ### end Alembic commands ###
